import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import '../models/chipviewlayout1_item_model.dart';import '../models/chipviewlayout3_item_model.dart';import 'package:kanza_s_application1/presentation/form_detail_screen/models/form_detail_model.dart';part 'form_detail_event.dart';part 'form_detail_state.dart';/// A bloc that manages the state of a FormDetail according to the event that is dispatched to it.
class FormDetailBloc extends Bloc<FormDetailEvent, FormDetailState> {FormDetailBloc(FormDetailState initialState) : super(initialState) { on<FormDetailInitialEvent>(_onInitialize); on<UpdateChipViewEvent>(_updateChipView); on<UpdateChipView1Event>(_updateChipView1); }

_updateChipView(UpdateChipViewEvent event, Emitter<FormDetailState> emit, ) { List<Chipviewlayout1ItemModel> newList = List<Chipviewlayout1ItemModel>.from(state.formDetailModelObj!.chipviewlayout1ItemList); newList[event.index] = newList[event.index].copyWith(isSelected: event.isSelected); emit(state.copyWith(formDetailModelObj: state.formDetailModelObj?.copyWith(chipviewlayout1ItemList: newList))); } 
_updateChipView1(UpdateChipView1Event event, Emitter<FormDetailState> emit, ) { List<Chipviewlayout3ItemModel> newList = List<Chipviewlayout3ItemModel>.from(state.formDetailModelObj!.chipviewlayout3ItemList); newList[event.index] = newList[event.index].copyWith(isSelected: event.isSelected); emit(state.copyWith(formDetailModelObj: state.formDetailModelObj?.copyWith(chipviewlayout3ItemList: newList))); } 
List<Chipviewlayout1ItemModel> fillChipviewlayout1ItemList() { return List.generate(2, (index) => Chipviewlayout1ItemModel()); } 
List<Chipviewlayout3ItemModel> fillChipviewlayout3ItemList() { return List.generate(5, (index) => Chipviewlayout3ItemModel()); } 
_onInitialize(FormDetailInitialEvent event, Emitter<FormDetailState> emit, ) async  { emit(state.copyWith(formPasswordController: TextEditingController())); emit(state.copyWith(formDetailModelObj: state.formDetailModelObj?.copyWith(chipviewlayout1ItemList: fillChipviewlayout1ItemList(), chipviewlayout3ItemList: fillChipviewlayout3ItemList()))); } 
 }
